### PR TITLE
Update linters script

### PR DESCRIPTION
**Pull request by Diegogagan2587**
# Implemented Changes:

we have updated the script `lint` in `package.json` in order to run all installed linting tools on this project with 
a single command, son when you type `npm run lint` in your console the next linting tools will run:
- eslint
- styleint

This will avoid  the developer having to run `npx eslint "**/*.{js,jsx}"` and `npx stylelint "**/*.{css,scss}"` separately in 
the console, but run them together instead with a single command `npm run lint` which is easier to remember.

### CODE REVIEW

**Review by danifromecuador — CHANGES_REQUESTED** [review]
## Pull Request Rejection

Dear [Diego](@Diegogagan2587 ),

Thank you for your contribution to the project! I appreciate the time and effort you've put into this pull request. However, after careful review, I've decided not to merge it at this time.

giphy

### Reasons for Rejection

1.  The command `npm run lint` is working well, but I've found a little issue:
   If there are errors in both JS and CSS files, that command shows only JS errors, so the tester or user needs to fix all the   JS errors and re-run the `npm run lint` command to see the CSS errors. This behavior can introduce misunderstandings because the user can think that all the JS & CSS linters errors are solved when there are still some CSS errors. 
Before introducing JSX linters errors: 
image
as you can see, the CSS errors are being shown
After introducing JSX linters errors: 
image
as you can see, the CSS errors are NOT being shown

### Next Steps

I encourage you to address the feedback provided and resubmit the pull request. Feel free to reach out if you have any questions or need further clarification.

### Optional Suggestions

1. Review this warning `29:6  warning  React Hook useEffect has missing dependencies: 'API_URL_BASE' and 'token'. Either include them or remove the dependency array  react-hooks/exhaustive-deps` 
at this component `/home/dani/WD/Book-a-concert-front-end/src/pages/DeleteConcertPage.jsx`
when running this command `npm run lint`

Thank you again for your contribution and understanding.

Best regards,
[Dani](@danifromecuador )

**Comment by Diegogagan2587** [comment]
@danifromecuador Thanks so much for noting that out, I think that yeah, it's important to see at once all the linting errors to get a better perspective about what we are doing wrong, so I 'll correct, thanks! and regarding to your optional suggestion is something I'm working on in a different branch, thanks!

**Comment by Diegogagan2587** [comment]
@danifromecuador After updating the script, now it will show both ESlint and Stylint results, I have added errors only in my local repo to generate some failings in linting tools to verify this behavior:
image


If there is something else let me know! thanks @danifromecuador

**Review by danifromecuador — APPROVED** [review]
## Congratulations 

Dear [Diego](@Diegogagan2587 ), your PR is approved, you made a great effort and now both ESLint and Stylelint errors are being shown.
giphy



There is nothing else to say than:  
### Merge It!

**Pull request merged**
