### PR TITLE
Test/item data panel

### PR DESCRIPTION
**Pull request by Diegogagan2587**
# Implemented Changes
In this pull request we create a tests file for the `ItemDataPanel.jsx` Component, and we are testing the next
- The component renders witouth crashing
- The component renders properly concert's data
- The reserve button redirects to reserve

image

### CODE REVIEW

**Review by danifromecuador — CHANGES_REQUESTED** [review]
## Pull Request Rejection

Dear [Diego](@Diegogagan2587 ),

Thank you for your contribution to the project! I appreciate the time and effort you've put into this pull request. However, after careful review, I've decided not to merge it at this time.

giphy

### Reasons for Rejection

1.  Your test `src/components/itemDataPanel.test.jsx` is passing successfully, as shown in this image
pass
but when I try to run all the other tests, some of them are not passing: 
image
I think this issue is something related to the `.env` file and its base URL 

### Next Steps

I encourage you to address the feedback provided and resubmit the pull request. Feel free to reach out if you have any questions or need further clarification.

Thank you again for your contribution and understanding.

Best regards,
[Dani](@danifromecuador )

**Comment by Diegogagan2587** [comment]
@danifromecuador Thanks for sharing your comments, I've updated the URL, so now the tests will get the base URL to be intercepted from the.env file, avoiding problems on each local development environment, this should fix the issue with some test not passing because they were not intercepting the request from components to the API

**Review by danifromecuador — APPROVED** [review]
## Congratulations 

Dear [Diego](@Diegogagan2587 ), your PR is approved, you made a great effort and now all the tests are passing.
giphy



There is nothing else to say than:  
### Merge It!

**Review by danifromecuador — APPROVED** [review]

**Comment by Diegogagan2587** [comment]
@danifromecuador Thanks for your insights buddy!

**Pull request merged**
