### PR TITLE
Feat/item page or concert details [Layout ONLY]

### PR DESCRIPTION
**Pull request by Diegogagan2587**
# Implemented Changes:

- [x] Create `Concert Details`/`items-details` first version layout
    - [x] Include Panel with placeholder data for current concert (No logic yet, only layout)
    - [x] Include placeholder image (no logic yet, generig img)
    - [x] include `reserve` button instead of config (only layout)
    - [x] Include a gob back button (only layout)
    - [x] Page is responsive

image

image

### CODE REVIEW

**Review by danifromecuador — CHANGES_REQUESTED** [review]
Hi @Diegogagan2587  

## STATUS: Changes required!
Great job so far 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!

almost

## Highlights
 - The mobile version is working as expected ✅
 - You did a great job using Tailwind for styling the page ✅
 
## Required Changes ♻️
- Please ensure that the text on the right does not extend beyond the top limit of the image. Additionally, make sure to place the reserve button at the bottom of the image, as per the provided design. This will help maintain the design's consistency across different screens and zoom levels.
image



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Please check this issue in the browser console: `(index):62 cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @danifromecuador .

**Comment by Diegogagan2587** [comment]
@danifromecuador Thanks for pointing that out, I didn't notice how the component would look outside my `testing container`, So I would make sure it will not change to an undesired shape in another place, Thanks for reviewing, will make corrections tomorrow morning!

**Comment by Diegogagan2587** [comment]
@danifromecuador Position Fixed:

# Fixed ! 

## Large Size
image

## Medium Size: 
image

# small size or mobile:
image

**Review by danifromecuador — APPROVED** [review]
Hi @Diegogagan2587  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
 - All project requirements have been implemented ✅ 
 
chuck-norris-thumbs-up

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @danifromecuador .

**Pull request merged**
